//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordVoyagerMVC.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using WordVoyagerMVC.Models;

    public partial class WordVoyagerEntities : DbContext
    {
        public WordVoyagerEntities()
            : base("name=WordVoyagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            
        }

        public virtual DbSet<UsersModel> UsersModels { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int uspDeleteArticleByArticleId(Nullable<int> articleId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteArticleByArticleId", articleIdParameter);
        }
    
        public virtual int uspDeleteArticleTag(Nullable<int> articleId, Nullable<int> tagId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            var tagIdParameter = tagId.HasValue ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteArticleTag", articleIdParameter, tagIdParameter);
        }
    
        public virtual int uspDeleteAttachmentByArticleIdAndAttchmentId(Nullable<int> articleId, Nullable<int> attachmentId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            var attachmentIdParameter = attachmentId.HasValue ?
                new ObjectParameter("AttachmentId", attachmentId) :
                new ObjectParameter("AttachmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteAttachmentByArticleIdAndAttchmentId", articleIdParameter, attachmentIdParameter);
        }
    
        public virtual int uspDeleteCategoryByCategoryId(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteCategoryByCategoryId", categoryIdParameter);
        }
    
        public virtual int uspDeleteCommentByCommentId(Nullable<int> commentId)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("CommentId", commentId) :
                new ObjectParameter("CommentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteCommentByCommentId", commentIdParameter);
        }
    
        public virtual int uspDeleteEmployee(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteEmployee", employeeIdParameter);
        }
    
        public virtual int uspDeleteTagByTagId(Nullable<int> tagId)
        {
            var tagIdParameter = tagId.HasValue ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteTagByTagId", tagIdParameter);
        }
    
        public virtual int uspDeleteUserByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspDeleteUserByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<uspGetAllArticles_Result> uspGetAllArticles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAllArticles_Result>("uspGetAllArticles");
        }
    
        public virtual ObjectResult<uspGetAllAttachementsByArticleId_Result> uspGetAllAttachementsByArticleId(Nullable<int> articleId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAllAttachementsByArticleId_Result>("uspGetAllAttachementsByArticleId", articleIdParameter);
        }
    
        public virtual ObjectResult<uspGetAllCategories_Result> uspGetAllCategories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAllCategories_Result>("uspGetAllCategories");
        }
    
        public virtual ObjectResult<uspGetAllTags_Result> uspGetAllTags()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAllTags_Result>("uspGetAllTags");
        }
    
        public virtual ObjectResult<uspGetAllUsers_Result> uspGetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAllUsers_Result>("uspGetAllUsers");
        }
    
        public virtual ObjectResult<uspGetArticleByArticleId_Result> uspGetArticleByArticleId(Nullable<int> articleId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetArticleByArticleId_Result>("uspGetArticleByArticleId", articleIdParameter);
        }
    
        public virtual ObjectResult<uspGetArticleTagsByArticleId_Result> uspGetArticleTagsByArticleId(Nullable<int> articleId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetArticleTagsByArticleId_Result>("uspGetArticleTagsByArticleId", articleIdParameter);
        }
    
        public virtual ObjectResult<uspGetAttachementByArticleIdAndAttachmentId_Result> uspGetAttachementByArticleIdAndAttachmentId(Nullable<int> articleId, Nullable<int> attachmentId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            var attachmentIdParameter = attachmentId.HasValue ?
                new ObjectParameter("AttachmentId", attachmentId) :
                new ObjectParameter("AttachmentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetAttachementByArticleIdAndAttachmentId_Result>("uspGetAttachementByArticleIdAndAttachmentId", articleIdParameter, attachmentIdParameter);
        }
    
        public virtual ObjectResult<uspGetCategoryByCategoryId_Result> uspGetCategoryByCategoryId(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetCategoryByCategoryId_Result>("uspGetCategoryByCategoryId", categoryIdParameter);
        }
    
        public virtual ObjectResult<uspGetCommentsByArticleId_Result> uspGetCommentsByArticleId(Nullable<int> articleId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetCommentsByArticleId_Result>("uspGetCommentsByArticleId", articleIdParameter);
        }
    
        public virtual ObjectResult<uspGetEmployeeByEmployeeId_Result> uspGetEmployeeByEmployeeId(Nullable<int> employeeId)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetEmployeeByEmployeeId_Result>("uspGetEmployeeByEmployeeId", employeeIdParameter);
        }
    
        public virtual ObjectResult<uspGetEmployeeRecords_Result> uspGetEmployeeRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetEmployeeRecords_Result>("uspGetEmployeeRecords");
        }
    
        public virtual ObjectResult<uspGetUserByUserId_Result> uspGetUserByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetUserByUserId_Result>("uspGetUserByUserId", userIdParameter);
        }
    
        public virtual int uspInsertArticle(string title, string content, Nullable<int> authorId, Nullable<int> categoryId)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var authorIdParameter = authorId.HasValue ?
                new ObjectParameter("AuthorId", authorId) :
                new ObjectParameter("AuthorId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertArticle", titleParameter, contentParameter, authorIdParameter, categoryIdParameter);
        }
    
        public virtual int uspInsertArticleTag(Nullable<int> articleId, Nullable<int> tagId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            var tagIdParameter = tagId.HasValue ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertArticleTag", articleIdParameter, tagIdParameter);
        }
    
        public virtual int uspInsertAttachment(Nullable<int> articleId, string fileName, string fileType, string filePath)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var fileTypeParameter = fileType != null ?
                new ObjectParameter("FileType", fileType) :
                new ObjectParameter("FileType", typeof(string));
    
            var filePathParameter = filePath != null ?
                new ObjectParameter("FilePath", filePath) :
                new ObjectParameter("FilePath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertAttachment", articleIdParameter, fileNameParameter, fileTypeParameter, filePathParameter);
        }
    
        public virtual int uspInsertCategory(string name, string description)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertCategory", nameParameter, descriptionParameter);
        }
    
        public virtual int uspInsertComment(Nullable<int> articleId, Nullable<int> userId, string content)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertComment", articleIdParameter, userIdParameter, contentParameter);
        }
    
        public virtual int uspInsertEmployee(string name, string designation, string department, ObjectParameter employeeId)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertEmployee", nameParameter, designationParameter, departmentParameter, employeeId);
        }
    
        public virtual int uspInsertTag(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertTag", nameParameter);
        }
    
        public virtual int uspInsertUser(string userName, string email, string passwordHash)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspInsertUser", userNameParameter, emailParameter, passwordHashParameter);
        }
    
        public virtual int uspUpdateArticleByArticleId(Nullable<int> articleId, string title, string content, Nullable<int> categoryId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateArticleByArticleId", articleIdParameter, titleParameter, contentParameter, categoryIdParameter);
        }
    
        public virtual int uspUpdateCategoryByCategoryId(Nullable<int> categoryId, string name, string description)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateCategoryByCategoryId", categoryIdParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int uspUpdateCommentByCommentId(Nullable<int> commentId, string content)
        {
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("CommentId", commentId) :
                new ObjectParameter("CommentId", typeof(int));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateCommentByCommentId", commentIdParameter, contentParameter);
        }
    
        public virtual int uspUpdateEmployeeDepartment(Nullable<int> employeeId, string department)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateEmployeeDepartment", employeeIdParameter, departmentParameter);
        }
    
        public virtual int uspUpdateEmployeeDesignation(Nullable<int> employeeId, string designation)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateEmployeeDesignation", employeeIdParameter, designationParameter);
        }
    
        public virtual int uspUpdateEmployeeDetails(Nullable<int> employeeId, string name, string designation, string department)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateEmployeeDetails", employeeIdParameter, nameParameter, designationParameter, departmentParameter);
        }
    
        public virtual int uspUpdateEmployeeName(Nullable<int> employeeId, string name)
        {
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateEmployeeName", employeeIdParameter, nameParameter);
        }
    
        public virtual int uspUpdateTagNameByTagId(Nullable<int> tagId, string name)
        {
            var tagIdParameter = tagId.HasValue ?
                new ObjectParameter("TagId", tagId) :
                new ObjectParameter("TagId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateTagNameByTagId", tagIdParameter, nameParameter);
        }
    
        public virtual int uspUpdateUserByUserId(Nullable<int> userId, string userName, string email, string passwordHash)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspUpdateUserByUserId", userIdParameter, userNameParameter, emailParameter, passwordHashParameter);
        }

        public System.Data.Entity.DbSet<WordVoyagerMVC.Models.TagModel> TagModels { get; set; }

        public System.Data.Entity.DbSet<WordVoyagerMVC.Models.CategoriesModel> CategoriesModels { get; set; }
    }
}
